services:
  - type: web
    name: snowflakes-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_TOKEN
        fromSecret: your-telegram-bot-token
